### ISSUE TITLE
can't "open with terminal" linux ubuntu

### ISSUE THREAD

**Issue by 6dyfer** [PeachyPeachSM64/sm64ex-omm#10]

**Comment by PeachyPeachSM64** [comment]
...
Can you please elaborate?
What do you mean by "can't open with terminal"?
What steps did you do to come to this conclusion?

**Comment by 6dyfer** [comment]
the option "open with terminal" does not show up

**Comment by PeachyPeachSM64** [comment]
Are you kidding me????
Are you really expecting an "Open with terminal" option to show up when right-clicking on a file???
This has to be a joke...
There are instructions on how to use the program on the very first page of this github!
And you clearly didn't read them!
Now, I'm closing this issue because it's definitely your problem, not mine.
Stop wasting my time by creating pointless issues.

**Comment by 6dyfer** [comment]
I am sorry :(
