### ISSUE TITLE
SMSR 2 Stars Impossible to get with "stay in level"

### ISSUE THREAD

**Issue by SapphireBulletBill** [PeachyPeachSM64/sm64ex-omm#17]
2 impossible stars to get when all acts are available
- Precision Swimming in Colorful Coral Caverns is blocked off
- A star in bob-omb battle factory where the vents and fires are turned on.

**Comment by PeachyPeachSM64** [comment]
Please precise if your issue is about Rebirth by adding `[Rebirth]` in your message title. I guessed it was, but that would save time for both of us.
- This has been fixed and star 4 of CCC can now be obtained in all modes. Please download `omm-coop.zip` again.
- Are you refering to star 6? In "Odyssey" and "Non-Stop" modes, star 6 has been relocated, since it overlaps with star 1 in these modes. To reach it, enter the pipe right before star 1.
